/*
 * Copyright 1999-2018 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

CREATE TABLE "NACOS"."CONFIG_INFO"
(
    "ID"                 BIGINT IDENTITY(1,1) NOT NULL,
    "DATA_ID"            VARCHAR(255) NOT NULL,
    "GROUP_ID"           VARCHAR(128) NULL,
    "CONTENT"            CLOB         NOT NULL,
    "MD5"                VARCHAR(32) NULL,
    "GMT_CREATE"         TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "GMT_MODIFIED"       TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "SRC_USER"           TEXT NULL,
    "SRC_IP"             VARCHAR(50) NULL,
    "APP_NAME"           VARCHAR(128) NULL,
    "TENANT_ID"          VARCHAR(128) DEFAULT '' NULL,
    "C_DESC"             VARCHAR(256) NULL,
    "C_USE"              VARCHAR(64) NULL,
    "EFFECT"             VARCHAR(64) NULL,
    "TYPE"               VARCHAR(64) NULL,
    "C_SCHEMA"           TEXT NULL,
    "ENCRYPTED_DATA_KEY" TEXT         NOT NULL
);

CREATE TABLE "NACOS"."CONFIG_INFO_GRAY"
(
    "ID"                 BIGINT IDENTITY(1,1) NOT NULL,
    "DATA_ID"            VARCHAR(255) NOT NULL,
    "GROUP_ID"           VARCHAR(128) NOT NULL,
    "CONTENT"            CLOB         NOT NULL,
    "MD5"                VARCHAR(32) NULL,
    "SRC_USER"           TEXT NULL,
    "SRC_IP"             VARCHAR(100) NULL,
    "GMT_CREATE"         TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "GMT_MODIFIED"       TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "APP_NAME"           VARCHAR(128) NULL,
    "TENANT_ID"          VARCHAR(128) DEFAULT '' NULL,
    "GRAY_NAME"          VARCHAR(128) NOT NULL,
    "GRAY_RULE"          TEXT         NOT NULL,
    "ENCRYPTED_DATA_KEY" TEXT         NOT NULL
);

CREATE TABLE "NACOS"."CONFIG_TAGS_RELATION"
(
    "ID"        BIGINT       NOT NULL,
    "TAG_NAME"  VARCHAR(128) NOT NULL,
    "TAG_TYPE"  VARCHAR(64) NULL,
    "DATA_ID"   VARCHAR(255) NOT NULL,
    "GROUP_ID"  VARCHAR(128) NOT NULL,
    "TENANT_ID" VARCHAR(128) DEFAULT '' NULL,
    "NID"       BIGINT IDENTITY(1,1) NOT NULL
);

CREATE TABLE "NACOS"."GROUP_CAPACITY"
(
    "ID"                BIGINT IDENTITY(1,1) NOT NULL,
    "GROUP_ID"          VARCHAR(128) DEFAULT '' NOT NULL,
    "QUOTA"             BIGINT       DEFAULT 0 NOT NULL,
    "USAGE"             BIGINT       DEFAULT 0 NOT NULL,
    "MAX_SIZE"          BIGINT       DEFAULT 0 NOT NULL,
    "MAX_AGGR_COUNT"    BIGINT       DEFAULT 0 NOT NULL,
    "MAX_AGGR_SIZE"     BIGINT       DEFAULT 0 NOT NULL,
    "MAX_HISTORY_COUNT" BIGINT       DEFAULT 0 NOT NULL,
    "GMT_CREATE"        TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "GMT_MODIFIED"      TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL
);

CREATE TABLE "NACOS"."HIS_CONFIG_INFO"
(
    "ID"                 DECIMAL(20, 0) NOT NULL,
    "NID"                BIGINT IDENTITY(1,1) NOT NULL,
    "DATA_ID"            VARCHAR(255) NOT NULL,
    "GROUP_ID"           VARCHAR(128) NOT NULL,
    "APP_NAME"           VARCHAR(128) NULL,
    "CONTENT"            CLOB         NOT NULL,
    "MD5"                VARCHAR(32) NULL,
    "GMT_CREATE"         TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "GMT_MODIFIED"       TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "SRC_USER"           TEXT NULL,
    "SRC_IP"             VARCHAR(50) NULL,
    "OP_TYPE"            CHAR(10) NULL,
    "TENANT_ID"          VARCHAR(128) DEFAULT '' NULL,
    "ENCRYPTED_DATA_KEY" TEXT         NOT NULL,
    "PUBLISH_TYPE"       VARCHAR(50)  DEFAULT 'formal' NULL,
    "GRAY_NAME"          VARCHAR(50)  DEFAULT NULL,
    "EXT_INFO"           TEXT DEFAULT NULL
);

CREATE TABLE "NACOS"."TENANT_CAPACITY"
(
    "ID"                BIGINT IDENTITY(1,1) NOT NULL,
    "TENANT_ID"         VARCHAR(128) DEFAULT '' NOT NULL,
    "QUOTA"             BIGINT       DEFAULT 0 NOT NULL,
    "USAGE"             BIGINT       DEFAULT 0 NOT NULL,
    "MAX_SIZE"          BIGINT       DEFAULT 0 NOT NULL,
    "MAX_AGGR_COUNT"    BIGINT       DEFAULT 0 NOT NULL,
    "MAX_AGGR_SIZE"     BIGINT       DEFAULT 0 NOT NULL,
    "MAX_HISTORY_COUNT" BIGINT       DEFAULT 0 NOT NULL,
    "GMT_CREATE"        TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "GMT_MODIFIED"      TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL
);

CREATE TABLE "NACOS"."TENANT_INFO"
(
    "ID"            BIGINT IDENTITY(1,1) NOT NULL,
    "KP"            VARCHAR(128) NOT NULL,
    "TENANT_ID"     VARCHAR(128) DEFAULT '' NULL,
    "TENANT_NAME"   VARCHAR(128) DEFAULT '' NULL,
    "TENANT_DESC"   VARCHAR(256) NULL,
    "CREATE_SOURCE" VARCHAR(32) NULL,
    "GMT_CREATE"    BIGINT       NOT NULL,
    "GMT_MODIFIED"  BIGINT       NOT NULL
);

CREATE TABLE "NACOS"."USERS"
(
    "USERNAME" VARCHAR(50)  NOT NULL,
    "PASSWORD" VARCHAR(500) NOT NULL,
    "ENABLED"  TINYINT      NOT NULL
);

CREATE TABLE "NACOS"."ROLES"
(
    "USERNAME" VARCHAR(50) NOT NULL,
    "ROLE"     VARCHAR(50) NOT NULL
);

CREATE TABLE "NACOS"."PERMISSIONS"
(
    "ROLE"     VARCHAR(50)  NOT NULL,
    "RESOURCE" VARCHAR(128) NOT NULL,
    "ACTION"   VARCHAR(8)   NOT NULL
);

CREATE TABLE "NACOS"."CONFIG_INFO_BETA"
(
    "ID"                 BIGINT IDENTITY(1,1) NOT NULL,
    "DATA_ID"            VARCHAR(255) NOT NULL,
    "GROUP_ID"           VARCHAR(128) NOT NULL,
    "TENANT_ID"          VARCHAR(128) DEFAULT '' NULL,
    "APP_NAME"           VARCHAR(128) NULL,
    "CONTENT"            CLOB NULL,
    "BETA_IPS"           VARCHAR(1024) NULL,
    "MD5"                VARCHAR(32) NULL,
    "GMT_CREATE"         TIMESTAMP(0) DEFAULT '2010-05-05 00:00:00' NOT NULL,
    "GMT_MODIFIED"       TIMESTAMP(0) DEFAULT '2010-05-05 00:00:00' NOT NULL,
    "SRC_USER"           VARCHAR(128) NULL,
    "SRC_IP"             VARCHAR(50) NULL,
    "ENCRYPTED_DATA_KEY" TEXT NULL
);

CREATE TABLE "NACOS"."CONFIG_INFO_TAG"
(
    "ID"           BIGINT IDENTITY(1,1) NOT NULL,
    "DATA_ID"      VARCHAR(255) NOT NULL,
    "GROUP_ID"     VARCHAR(128) NOT NULL,
    "TENANT_ID"    VARCHAR(128) DEFAULT '' NULL,
    "TAG_ID"       VARCHAR(128) NOT NULL,
    "APP_NAME"     VARCHAR(128) NULL,
    "CONTENT"      CLOB         NOT NULL,
    "MD5"          VARCHAR(32) NULL,
    "GMT_CREATE"   TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "GMT_MODIFIED" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "SRC_USER"     TEXT NULL,
    "SRC_IP"       VARCHAR(50) NULL
);

CREATE TABLE "NACOS"."PIPELINE_EXECUTION"
(
    "EXECUTION_ID"  VARCHAR(64)  NOT NULL,
    "RESOURCE_TYPE" VARCHAR(32)  NOT NULL,
    "RESOURCE_NAME" VARCHAR(256) NOT NULL,
    "NAMESPACE_ID"  VARCHAR(128) DEFAULT NULL,
    "VERSION"       VARCHAR(64)  DEFAULT NULL,
    "STATUS"        VARCHAR(32)  NOT NULL,
    "PIPELINE"      CLOB         NOT NULL,
    "CREATE_TIME"   BIGINT(20)   NOT NULL,
    "UPDATE_TIME"   BIGINT(20)   NOT NULL
);

CREATE TABLE "NACOS"."AI_RESOURCE"
(
    "ID"            BIGINT IDENTITY(1,1) NOT NULL,
    "GMT_CREATE"    TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "GMT_MODIFIED"  TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "NAME"          VARCHAR(256) NOT NULL,
    "TYPE"          VARCHAR(32)  NOT NULL,
    "C_DESC"        VARCHAR(2048) DEFAULT NULL,
    "STATUS"        VARCHAR(32) DEFAULT NULL,
    "NAMESPACE_ID"  VARCHAR(128) DEFAULT '' NOT NULL,
    "BIZ_TAGS"      VARCHAR(1024) DEFAULT NULL,
    "EXT"           TEXT DEFAULT NULL,
    "C_FROM"        VARCHAR(256) DEFAULT 'local' NOT NULL,
    "VERSION_INFO"  TEXT DEFAULT NULL,
    "META_VERSION"  BIGINT(20)   DEFAULT 1 NOT NULL,
    "SCOPE"         VARCHAR(16)  DEFAULT 'PRIVATE' NOT NULL,
    "OWNER"         VARCHAR(128) DEFAULT '' NOT NULL,
    "DOWNLOAD_COUNT" BIGINT(20)  DEFAULT 0 NOT NULL
);

CREATE TABLE "NACOS"."AI_RESOURCE_VERSION"
(
    "ID"                    BIGINT IDENTITY(1,1) NOT NULL,
    "GMT_CREATE"            TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "GMT_MODIFIED"          TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    "TYPE"                  VARCHAR(32)  NOT NULL,
    "AUTHOR"                VARCHAR(128) DEFAULT NULL,
    "NAME"                  VARCHAR(256) NOT NULL,
    "C_DESC"                VARCHAR(2048) DEFAULT NULL,
    "STATUS"                VARCHAR(32) NOT NULL,
    "VERSION"               VARCHAR(64)  NOT NULL,
    "NAMESPACE_ID"          VARCHAR(128) DEFAULT '' NOT NULL,
    "STORAGE"               TEXT DEFAULT NULL,
    "PUBLISH_PIPELINE_INFO" TEXT DEFAULT NULL,
    "DOWNLOAD_COUNT"        BIGINT(20)   DEFAULT 0 NOT NULL
);

ALTER TABLE "NACOS"."CONFIG_INFO"
    ADD CONSTRAINT PRIMARY KEY ("ID");

ALTER TABLE "NACOS"."CONFIG_INFO"
    ADD CONSTRAINT "UK_CONFIGINFO_DATAGROUPTENANT" UNIQUE ("DATA_ID", "GROUP_ID", "TENANT_ID");

ALTER TABLE "NACOS"."CONFIG_INFO_GRAY"
    ADD CONSTRAINT PRIMARY KEY ("ID");

ALTER TABLE "NACOS"."CONFIG_INFO_GRAY"
    ADD CONSTRAINT "UK_CONFIGINFOGRAY_DATAGROUPTENANTGRAY" UNIQUE ("DATA_ID", "GROUP_ID", "TENANT_ID", "GRAY_NAME");

CREATE INDEX "IDX_DATAID_GMT_MODIFIED" ON "NACOS"."CONFIG_INFO_GRAY" ("DATA_ID", "GMT_MODIFIED");

CREATE INDEX "IDX_GRAY_GMT_MODIFIED" ON "NACOS"."CONFIG_INFO_GRAY" ("GMT_MODIFIED");

ALTER TABLE "NACOS"."CONFIG_TAGS_RELATION"
    ADD CONSTRAINT PRIMARY KEY ("NID");

ALTER TABLE "NACOS"."CONFIG_TAGS_RELATION"
    ADD CONSTRAINT "UK_CONFIGTAGRELATION_CONFIGIDTAG" UNIQUE ("ID", "TAG_NAME", "TAG_TYPE");

ALTER TABLE "NACOS"."GROUP_CAPACITY"
    ADD CONSTRAINT PRIMARY KEY ("ID");

ALTER TABLE "NACOS"."GROUP_CAPACITY"
    ADD CONSTRAINT "UK_GROUP_ID" UNIQUE ("GROUP_ID");

ALTER TABLE "NACOS"."HIS_CONFIG_INFO"
    ADD CONSTRAINT PRIMARY KEY ("NID");

CREATE INDEX "IDX_GMT_CREATE" ON "NACOS"."HIS_CONFIG_INFO" ("GMT_CREATE");

CREATE INDEX "IDX_GMT_MODIFIED" ON "NACOS"."HIS_CONFIG_INFO" ("GMT_MODIFIED");

CREATE INDEX "IDX_DID" ON "NACOS"."HIS_CONFIG_INFO" ("DATA_ID");

ALTER TABLE "NACOS"."TENANT_CAPACITY"
    ADD CONSTRAINT PRIMARY KEY ("ID");

ALTER TABLE "NACOS"."TENANT_CAPACITY"
    ADD CONSTRAINT "UK_TENANT_ID" UNIQUE ("TENANT_ID");

ALTER TABLE "NACOS"."TENANT_INFO"
    ADD CONSTRAINT PRIMARY KEY ("ID");

ALTER TABLE "NACOS"."TENANT_INFO"
    ADD CONSTRAINT "UK_TENANT_INFO_KPTENANTID" UNIQUE ("KP", "TENANT_ID");

CREATE INDEX "IDX_TENANT_ID" ON "NACOS"."TENANT_INFO" ("TENANT_ID");

ALTER TABLE "NACOS"."USERS"
    ADD CONSTRAINT PRIMARY KEY ("USERNAME");

ALTER TABLE "NACOS"."ROLES"
    ADD CONSTRAINT "IDX_USER_ROLE" UNIQUE ("USERNAME", "ROLE");

ALTER TABLE "NACOS"."PERMISSIONS"
    ADD CONSTRAINT "UK_ROLE_PERMISSION" UNIQUE ("ROLE", "RESOURCE", "ACTION");

ALTER TABLE "NACOS"."CONFIG_INFO_BETA"
    ADD CONSTRAINT PRIMARY KEY ("ID");

ALTER TABLE "NACOS"."CONFIG_INFO_BETA"
    ADD CONSTRAINT "UK_CONFIGINFOBETA_DATAGROUPTENANT" UNIQUE ("DATA_ID", "GROUP_ID", "TENANT_ID");

ALTER TABLE "NACOS"."CONFIG_INFO_TAG"
    ADD CONSTRAINT PRIMARY KEY ("ID");

ALTER TABLE "NACOS"."CONFIG_INFO_TAG"
    ADD CONSTRAINT "UK_CONFIGINFOTAG_DATAGROUPTENANTTAG" UNIQUE ("DATA_ID", "GROUP_ID", "TENANT_ID", "TAG_ID");

ALTER TABLE "NACOS"."PIPELINE_EXECUTION"
    ADD CONSTRAINT PRIMARY KEY ("EXECUTION_ID");

ALTER TABLE "NACOS"."AI_RESOURCE"
    ADD CONSTRAINT PRIMARY KEY ("ID");

ALTER TABLE "NACOS"."AI_RESOURCE"
    ADD CONSTRAINT "UK_AI_RESOURCE_NS_NAME_TYPE" UNIQUE ("NAMESPACE_ID", "NAME", "TYPE", "C_FROM");

CREATE INDEX "IDX_AI_RESOURCE_NAME" ON "NACOS"."AI_RESOURCE" ("NAME");

CREATE INDEX "IDX_AI_RESOURCE_TYPE" ON "NACOS"."AI_RESOURCE" ("TYPE");

CREATE INDEX "IDX_AI_RESOURCE_GMT_MODIFIED" ON "NACOS"."AI_RESOURCE" ("GMT_MODIFIED");

ALTER TABLE "NACOS"."AI_RESOURCE_VERSION"
    ADD CONSTRAINT PRIMARY KEY ("ID");

ALTER TABLE "NACOS"."AI_RESOURCE_VERSION"
    ADD CONSTRAINT "UK_AI_RESOURCE_VER_NS_NAME_TYPE_VER" UNIQUE ("NAMESPACE_ID", "NAME", "TYPE", "VERSION");

CREATE INDEX "IDX_AI_RESOURCE_VER_NAME" ON "NACOS"."AI_RESOURCE_VERSION" ("NAME");

CREATE INDEX "IDX_AI_RESOURCE_VER_STATUS" ON "NACOS"."AI_RESOURCE_VERSION" ("STATUS");

CREATE INDEX "IDX_AI_RESOURCE_VER_GMT_MODIFIED" ON "NACOS"."AI_RESOURCE_VERSION" ("GMT_MODIFIED");

INSERT INTO "NACOS"."USERS"("USERNAME", "PASSWORD", "ENABLED")
VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);

INSERT INTO "NACOS"."ROLES"("USERNAME", "ROLE")
VALUES ('nacos', 'ROLE_ADMIN');